FROM php:8.4-cli-alpine
RUN apk add --no-cache git unzip
RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath opcache
RUN apk add --no-cache autoconf g++ make \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && apk del autoconf g++ make
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
WORKDIR /var/www/html
COPY . .
RUN composer install --no-dev --optimize-autoloader --no-interaction
CMD ["php", "artisan", "horizon"]
